### PR TITLE
Upgrade richie to v2.29.2

### PR DESCRIPTION
**Pull request by Tiago-Salles**
This PR updates richie to v2.29.2.

The considerable change is related with the `git+https://github.com/openfun/django-cms@fun-3.11.6#egg=django-cms` package installation that was removed from the docker file and inserted to base.txt as the openfun [commit](https://github.com/openfun/fun-richie-site-factory/commit/02a9cef03b3c6f58b9aeda6a223963f2efa700df#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557t).

This PR is related to: Upgrade richie to v2.29.1 on nau-richie-site-factory https://github.com/fccn/nau-richie-site-factory/issues/261

### CODE REVIEW

**Comment by sandroscosta** [comment]
@igobranco and @Tiago-Salles please test this again. It's working now but I need further confirmation.

**Comment by igobranco** [comment]
@sandroscosta and @Tiago-Salles I confirm that it is working fine now!

**Comment by igobranco** [comment]
Nevertheless, I think we should remove the bump of new release on this branch.
@Tiago-Salles please create a new PR with your upgrade. Then cherry pick @sandroscosta fix on top.

**Comment by Tiago-Salles** [comment]
@sandroscosta and @igobranco I can confirm as well that it works to me. Now @sandroscosta I will squash these commits using your as the main one.

**Comment by igobranco** [comment]
@Tiago-Salles  add a line to the [CHANGELOG.md](https://github.com/fccn/nau-richie-site-factory/blob/master/sites/nau/CHANGELOG.md).

Like:
```
⬆️(nau) upgrade richie to v2.....
```

**Comment by igobranco** [comment]
Closing, the NAU site has been upgraded 2.32.0 on https://github.com/fccn/nau-richie-site-factory/pull/278

**Pull request closed without merging**
