### PR TITLE
Add Lilac adapter with custom error payload

### PR DESCRIPTION
**Pull request by sandroscosta**
✅ (jest) add jest tests to site factory
:sparkles: (api) update openedx-hawthorn adapter

### CODE REVIEW

**Comment by sandroscosta** [comment]
Yarn is running with `--frozen-lockfile`, but it needs to run without it, because the packages changed.

**Comment by sandroscosta** [comment]
https://circleci.com/developer/orbs/orb/circleci/node

**Comment by igobranco** [comment]
@sandroscosta  we need this to run on circleci.

**Comment by igobranco** [comment]
💪🎉🍾

**Review by igobranco — APPROVED** [review]

**Pull request merged**
