### PR TITLE
💄(footer) refactor footer logos placeholder

### PR DESCRIPTION
**Pull request by sandroscosta**
Changed the footer placeholder. It now holds sections to create rows of icons.

Use Richie sections to create new rows of logos. Due to flex-box, they'll float accordingly

image

### CODE REVIEW

**Comment by igobranco** [comment]
@sandroscosta 
It raises me this error:
image

This is still in draft, right?

**Comment by sandroscosta** [comment]
I'm going to check that out.

**Comment by igobranco** [comment]
@sandroscosta have you finish this?

**Comment by sandroscosta** [comment]
> @sandroscosta have you finish this?

I'm going to finish it this week. I need to test compatibility with DjangoCMS new placeholders to guarantee that everything is working properly,.

**Comment by sandroscosta** [comment]
@igobranco can you review?

**Comment by sandroscosta** [comment]
resolves #238

**Comment by igobranco** [comment]
The original footer logos links are:
- https://nau-prod-richie-nau-media.rgw.nau.fccn.pt/media/filer_public/2a/f5/2af51561-e2cd-4b12-8cbe-c62aca6e1727/barra.png
- https://nau-prod-richie-nau-media.rgw.nau.fccn.pt/media/filer_public/64/a7/64a7c11d-c3f8-4487-95c0-46b3f8bb5236/4logos-feder_fse_nau_v2.png

**Review by igobranco — APPROVED** [review]
LGTM ✔️

**Pull request merged**
